# Generated by Django 5.2 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
